In [ ]:
import tools


features = '''match_id, match_outcome, winning_team, hero_id, team, 
        match_mode, average_badge_team0, "stats.time_stamp_s", "stats.net_worth", 
        "mid_boss.destroyed_time_s", "mid_boss.team_claimed"'''

dataset = tools.get_match_dataframe(features, 1000)
heroes = tools.get_heroes_dataframe()

display(dataset)

    id         name
id
1    1     Infernus
2    2        Seven
3    3     Vindicta
4    4   Lady Geist
6    6       Abrams
7    7       Wraith
8    8     McGinnis
10  10      Paradox
11  11       Dynamo
12  12       Kelvin
13  13         Haze
14  14     Holliday
15  15        Bebop
16  16       Calico
17  17   Grey Talon
18  18   Mo & Krill
19  19         Shiv
20  20          Ivy
25  25       Warden
27  27       Yamato
31  31         Lash
35  35      Viscous
50  50       Pocket
52  52       Mirage
58  58        Vyper
60  60     Sinclair
63  63         Mina
64  64      Drifter
65  65      Venator
66  66       Victor
67  67        Paige
69  69  The Doorman
72  72        Billy
76  76       Graves
77  77       Apollo
79  79          Rem
80  80       Silver
81  81      Celeste

,match_id,match_outcome,winning_team,hero_id,team,match_mode,average_badge_team0,stats.time_stamp_s,stats.net_worth,mid_boss.destroyed_time_s,mid_boss.team_claimed
0,84031381,TeamWin,Team0,11,Team0,Unranked,94,"[180, 360, 540, 720, 900, 1200, 1500, 1763]","[1677, 3875, 5529, 8547, 10505, 17620, 26123, ...",[1433],[Team0]
1,84031381,TeamWin,Team0,17,Team1,Unranked,94,"[180, 360, 540, 720, 900, 1200, 1500, 1763]","[1776, 3355, 5355, 8274, 11176, 13844, 17776, ...",[1433],[Team0]
2,84031381,TeamWin,Team0,18,Team0,Unranked,94,"[180, 360, 540, 720, 900, 1200, 1500, 1763]","[1835, 3958, 6692, 10123, 11743, 18157, 26782,...",[1433],[Team0]
3,84031381,TeamWin,Team0,6,Team0,Unranked,94,"[180, 360, 540, 720, 900, 1200, 1500, 1763]","[2037, 3781, 6675, 11170, 13517, 21202, 29857,...",[1433],[Team0]
4,84031381,TeamWin,Team0,12,Team1,Unranked,94,"[180, 360, 540, 720, 900, 1200, 1500, 1763]","[2226, 4765, 7737, 11058, 13687, 18611, 26262,...",[1433],[Team0]
...,...,...,...,...,...,...,...,...,...,...,...
995,84122323,TeamWin,Team0,72,Team1,Unranked,101,"[180, 360, 540, 720, 900, 1200, 1500, 1800, 2071]","[1935, 3797, 5722, 9547, 14416, 21350, 24423, ...","[1308, 1902]","[Team0, Team0]"
996,84122324,TeamWin,Team0,17,Team1,Unranked,93,"[180, 360, 540, 720, 900, 1200, 1383]","[1628, 3291, 5171, 8486, 10862, 15263, 16890]",[1293],[Team0]
997,84122324,TeamWin,Team0,19,Team0,Unranked,93,"[180, 360, 540, 720, 900, 1200, 1383]","[1935, 3733, 7660, 11518, 15792, 25779, 33676]",[1293],[Team0]
998,84032412,TeamWin,Team1,11,Team1,Unranked,92,"[180, 360, 540, 720, 900, 1200, 1500, 1800, 1881]","[1841, 3439, 6033, 8824, 12750, 18934, 25940, ...",[1703],[Team1]
999,84032412,TeamWin,Team1,17,Team0,Unranked,92,"[180, 360, 540, 720, 900, 1200, 1500, 1800, 1881]","[2153, 4331, 7328, 9417, 12282, 19032, 24709, ...",[1703],[Team1]