In [1]:
import tools


features = '''match_id, match_outcome, winning_team, hero_id, team, 
        match_mode, average_badge_team0, "stats.time_stamp_s", "stats.net_worth", 
        "mid_boss.destroyed_time_s", "mid_boss.team_claimed"'''

dataset = tools.get_match_dataframe(features, 1000)
heroes = tools.get_heroes_dataframe()

display(dataset)

,match_id,match_outcome,winning_team,hero_id,team,match_mode,average_badge_team0,stats.time_stamp_s,stats.net_worth,mid_boss.destroyed_time_s,mid_boss.team_claimed
0,84031381,TeamWin,Team0,11,Team0,Unranked,94,"[180, 360, 540, 720, 900, 1200, 1500, 1763]","[1677, 3875, 5529, 8547, 10505, 17620, 26123, ...",[1433],[Team0]
1,84031381,TeamWin,Team0,17,Team1,Unranked,94,"[180, 360, 540, 720, 900, 1200, 1500, 1763]","[1776, 3355, 5355, 8274, 11176, 13844, 17776, ...",[1433],[Team0]
2,84031381,TeamWin,Team0,18,Team0,Unranked,94,"[180, 360, 540, 720, 900, 1200, 1500, 1763]","[1835, 3958, 6692, 10123, 11743, 18157, 26782,...",[1433],[Team0]
3,84031381,TeamWin,Team0,6,Team0,Unranked,94,"[180, 360, 540, 720, 900, 1200, 1500, 1763]","[2037, 3781, 6675, 11170, 13517, 21202, 29857,...",[1433],[Team0]
4,84031381,TeamWin,Team0,12,Team1,Unranked,94,"[180, 360, 540, 720, 900, 1200, 1500, 1763]","[2226, 4765, 7737, 11058, 13687, 18611, 26262,...",[1433],[Team0]
...,...,...,...,...,...,...,...,...,...,...,...
995,84122323,TeamWin,Team0,72,Team1,Unranked,101,"[180, 360, 540, 720, 900, 1200, 1500, 1800, 2071]","[1935, 3797, 5722, 9547, 14416, 21350, 24423, ...","[1308, 1902]","[Team0, Team0]"
996,84122324,TeamWin,Team0,17,Team1,Unranked,93,"[180, 360, 540, 720, 900, 1200, 1383]","[1628, 3291, 5171, 8486, 10862, 15263, 16890]",[1293],[Team0]
997,84122324,TeamWin,Team0,19,Team0,Unranked,93,"[180, 360, 540, 720, 900, 1200, 1383]","[1935, 3733, 7660, 11518, 15792, 25779, 33676]",[1293],[Team0]
998,84032412,TeamWin,Team1,11,Team1,Unranked,92,"[180, 360, 540, 720, 900, 1200, 1500, 1800, 1881]","[1841, 3439, 6033, 8824, 12750, 18934, 25940, ...",[1703],[Team1]
999,84032412,TeamWin,Team1,17,Team0,Unranked,92,"[180, 360, 540, 720, 900, 1200, 1500, 1800, 1881]","[2153, 4331, 7328, 9417, 12282, 19032, 24709, ...",[1703],[Team1]

In [2]:
tools.data_feature_preprocess(dataset, heroes, 1500)

,match_id,winning_team,mid_boss.team_claimed,1,2,3,4,6,7,8,...,65,66,67,69,72,76,77,79,80,81
0,84031381,Team0,1,0,0,-20364,0,29857,0,0,...,0,0,0,0,0,-20371,0,0,0,0
1,84031406,Team0,0,0,27798,0,-28656,0,0,0,...,0,0,0,0,0,-25389,0,0,0,0
2,84031463,Team0,1,0,0,0,26992,24094,0,28893,...,-23151,0,0,0,0,28303,0,0,0,-25717
3,84031479,Team0,-1,0,0,0,0,0,29284,0,...,-27098,-29918,26943,0,0,29825,0,0,-27313,0
4,84031490,Team1,1,0,-26856,0,0,27105,0,32362,...,0,0,0,25541,0,0,0,0,25508,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,84122296,Team0,1,29234,0,0,0,0,0,0,...,0,0,-28073,0,-25838,0,0,0,25437,0
81,84122307,Team1,0,-25597,0,-23680,0,-32232,32594,0,...,0,0,0,-23394,0,0,0,-25550,0,0
82,84122323,Team0,1,0,0,0,0,24562,0,0,...,0,31577,23995,0,-24423,0,0,-24710,0,0
83,84122324,Team0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
84,84032412,Team1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0